project:
  type: default
  render:
    - analysis/plants-per-state.qmd
  output-dir: _output
  execute-dir: project

bibliography: references.bib

format:
  html:
    toc: true
    number-sections: true
    fig-width: 8
    fig-height: 5
  docx:
    number-sections: true
    fig-width: 7
    fig-height: 4.5

execute:
  echo: false
  warning: false
  message: false
